// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTLiCfpO3g2NVxCzCTXHltEsf4Z8pD3LE',
    appId: '1:389357449292:web:e166a28bacc586f1cb04e9',
    messagingSenderId: '389357449292',
    projectId: 'my6-pro-note',
    authDomain: 'my6-pro-note.firebaseapp.com',
    storageBucket: 'my6-pro-note.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciqFwsPE1vTVmpAZJaEsspMAWmsI6dsU',
    appId: '1:389357449292:android:f19d94b6a3041d18cb04e9',
    messagingSenderId: '389357449292',
    projectId: 'my6-pro-note',
    storageBucket: 'my6-pro-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeUI1PlCTK97jkvAbRE9aT3jKzKKZrtQ',
    appId: '1:389357449292:ios:b0c586bd00a14084cb04e9',
    messagingSenderId: '389357449292',
    projectId: 'my6-pro-note',
    storageBucket: 'my6-pro-note.firebasestorage.app',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAeUI1PlCTK97jkvAbRE9aT3jKzKKZrtQ',
    appId: '1:389357449292:ios:b0c586bd00a14084cb04e9',
    messagingSenderId: '389357449292',
    projectId: 'my6-pro-note',
    storageBucket: 'my6-pro-note.firebasestorage.app',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTLiCfpO3g2NVxCzCTXHltEsf4Z8pD3LE',
    appId: '1:389357449292:web:8c7d4f3cb07c74d0cb04e9',
    messagingSenderId: '389357449292',
    projectId: 'my6-pro-note',
    authDomain: 'my6-pro-note.firebaseapp.com',
    storageBucket: 'my6-pro-note.firebasestorage.app',
  );
}
